language: node_js
node_js: 12
matrix:
  include:
  - os: osx
    osx_image: xcode10.2
  - os: linux
    sudo: required
    dist: xenial
    before_install:
    - sudo apt-get install --no-install-recommends -y libopenjp2-tools
    - sudo apt-get install --no-install-recommends -y rpm
    addons:
      snaps:
      - name: snapcraft
        classic: true
branches:
  except:
    - /^v?\d+.*$/
env:
  global:
  - GITHUB_REPO: bitshares/beet
  - secure: "AKaOWBQXHrukCIUFLoy6xaPigcrLlKLyO78ApdbS9zeoqVUKJamgkvpVoAo3KVtPTkEuWfD2LBFlc+OOv/3zECNynaEzy8gI/6IsUUm8DEIzg5phrImkcrW3E0rxJ1T5kQtXcAYDe36S9DhzN32qRb3YKOQgGeMykX+aTw432c3KcmYQ0HTQT6TdqXe6dmG4/nxZfbtUky45Nvp8YykyHr+TL1s9FDO+jEiaSBwnNxqYsWil60XqD1d6YPvzNuZdqwdhT+bdsDhHa9kx5d+3zPczCVW3Y5TtOtRoToyi6OUmEzUF1QwDu1fOj6u/vK1xZTys34R3RAWCUjYgF0uYx5bZbXGBQz1O0wjAdAj/XDpw0Z13zyXKxYHbNj2yY/Dy5NOMb75NEf4JkWa1uSWlEcpyCcYj6EZuKojNi1pOzAoi9uF6Z5nhc/8z6EqkPQIIz2cg1Q8MpzqL0an4wwS00xHBm5LrwqYumDqnputAjEh7VDp1ee+WazbNQqXO6d+GDzadpG7HK/f86lLW6fAkzyyCOn4CAS7Hl1wEO0DVRTzvOc8DETG4Usg2kYUYDY7OzZkWf1I9uLbZcro9RRqF0h/A7lSdnL1SiVawzLovz0+mvhx1C/BHr95Sco+voBqdIyH+LU+9c+4hIsId9n2Ze8iehdflehczymhFBVg5hNA="
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc
    - g++
    - icnsutils
    - build-essential
    - libopenjp2-tools
    - libstdc++6
    - graphicsmagick
    - xz-utils
    - fakeroot
    - rpm
    - libusb-dev
    - libudev-dev
    - rpm
install:
- npm ci
script:
- npm run build
- bash publish.sh
- test -s release_name && export RELEASE_NAME=$(cat release_name) && rm release_name
- test -s release_desc && export RELEASE_DESC=$(cat release_desc) && rm release_desc
- test -s travis_tag && export TRAVIS_TAG=$(cat travis_tag) && rm travis_tag
deploy:
  provider: releases
  file_glob: true
  api_key: $GH_TOKEN
  file: 
    - "dist/BeetSetup.deb"
    - "dist/BeetSetup.rpm"
    - "dist/BeetSetup.dmg"
    - "dist/BeetSetup.dmg.blockmap"
    - "dist/BeetSetup.zip"
    - "dist/BeetSetup.AppImage"
    - "dist/*.yml"
  skip_cleanup: true
  prerelease: true
  name: $RELEASE_NAME
  body: $RELEASE_DESC
  on:
    tags: true
    all_branches: true